language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

before_install:
  - mysql -e "create database IF NOT EXISTS comodojo;" -uroot
  - psql -c 'create database comodojo;' -U postgres

before_script:
  - composer install --prefer-source

script: ./vendor/bin/phpunit
